services:
  db:
    image: postgres:15
    container_name: sim-synaptic-db
    environment:
      POSTGRES_USER: glory
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sim_synaptic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: sim-synaptic-api
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://glory:1234@db:5432/sim_synaptic
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
